name: RPGRegions
version: '${version}'
main: net.islandearth.rpgregions.RPGRegions
api-version: '1.16'
libraries:
  - "com.zaxxer:HikariCP:5.0.1" # database
  - "net.kyori:adventure-platform-bukkit:4.3.1"
  - "net.kyori:adventure-text-minimessage:4.14.0"
  - "com.github.ben-manes.caffeine:caffeine:3.1.8"
  - "org.xerial:sqlite-jdbc:3.30.1"
  - "org.flywaydb:flyway-core:9.16.2" # db migration
  - "org.flywaydb:flyway-mysql:9.16.3"
softdepend: [Hyperverse, Multiverse-Core, UltraRegions, WorldGuard, PlaceholderAPI, HeadDatabase, Residence, Plan, GriefPrevention, GriefDefender, Vault, MythicMobs, AlonsoLevels, dynmap, ProtocolLib, Quests, BetonQuest, Lands, MMOCore, CustomStructures]
authors: [SamB440]
description: Discoverable regions
website: https://fortitude.islandearth.net
folia-supported: true
